name: object_detection_const_hp_distributed
labels:
  - "object detection"
  - "project blue"
  - "4 GPU"
environment:
  image: determinedaicustomer/determined-demo-object-detection:0.17.1
data:
  url: https://determined-ai-public-datasets.s3-us-west-2.amazonaws.com/PennFudanPed/PennFudanPed.zip
entrypoint: model_def:ObjectDetectionModel
hyperparameters:
  global_batch_size: 16
  learning_rate: 0.02
  momentum: 0.8
  weight_decay: 0.0005
min_validation_period:
  epochs: 4
records_per_epoch: 136
resources:
  slots_per_trial: 4
searcher:
  max_length:
    epochs: 4
  metric: val_avg_iou
  name: single
  smaller_is_better: false
profiling:
  enabled: true
  begin_on_batch: 0
  end_after_batch: null
max_restarts: 5
