name: MRI-test4-on-prem-4GPU
workspace: jordan-scratch 
project: brain-mri
data:
  data_dir:  '/data/lgg-mri-segmentation/kaggle_3m/'
  repo: 'mateuszbuda/brain-segmentation-pytorch'
  model: 'unet'
hyperparameters:
  global_batch_size: 512
  init_features: 32
  input_channels: 3
  output_channels: 1
  learning_rate: 0.0001
  weight_decay: 0.0
  pretrained: False # starting from pretrained unet model from PyTorch Hub - not necessary if loading weights from older trial
  split_seed: 1
  validation_ratio: 0.2
records_per_epoch: 3143 # 3143 for seed 1 and 2, we can consider seed 2 as our second 80/20 split
searcher:
  name: single
  metric: val_IoU
  smaller_is_better: False
  max_length:
    epochs: 25
  source_trial_id: 95 # id of trial corresponding to test1 - will start from latest trial checkpoint, could use source_checkpoint_uuid if we want to start from best checkpoint instead
min_validation_period:
  epochs: 1
resources:
  slots_per_trial: 4
  resource_pool: compute-pool-on-prem
max_restarts: 2
entrypoint: model_def:MRIUnetTrial
profiling:
  enabled: True

bind_mounts:
  - host_path: /mnt/data
    container_path: /data
    read_only: False 
checkpoint_storage:
  type: shared_fs
  host_path: /mnt/shared_fs